# Generated by Django 3.0.7 on 2020-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V7_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='n/a', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='n/a', max_length=200, unique=True),
        ),
    ]
