# Generated by Django 3.0.7 on 2021-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V7_products', '0003_auto_20201211_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
