# Generated by Django 3.0.7 on 2021-01-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V7_products', '0006_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('OFA', 'One Size Fits All'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Double Extra Large'), ('3XL', 'Triple Extra Large')], default='OFA', max_length=200),
        ),
    ]
